global using static CommonBasicLibraries.DatabaseHelpers.MiscClasses.SortInfo;
global using co1 = CommonBasicLibraries.DatabaseHelpers.ConditionClasses.ConditionOperators;
global using cs1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using static CommonBasicLibraries.BasicDataSettingsAndProcesses.VBCompat;
global using js1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.SystemTextJsonStrings;
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using dd1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.Constants;
global using aa1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.ApplicationPath;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using static CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.RandomGenerator.RandomGenerator.Data;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.MapHelpers;
global using CommonBasicLibraries.MediaHelpers.Models;
global using CommonBasicLibraries.MediaHelpers.Interfaces;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.FileProviders;
global using CommonBasicLibraries.CustomConfigurationProviders.Text;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.IConfigurationHelpers;
global using CommonBasicLibraries.DatabaseHelpers.AbstractStaticInterfaces;
global using System.Data; //unfortunately, needs some stuff with system.data anyways.
global using System.Data.Common;
global using System.Collections;
global using System.Threading;
global using tta1 = System.Timers;
